name: 'Kezios packaging & commit'

description: |
  This GitHub Action runs a packaging Node script to create new version & update changelog.

inputs:
  enable-commit-and-push: 
    description: 'Will create commit & push change'
    default: "true"
  
  staging-path:
    description: 'Args of "git add"'
    default: "."

  package-path:
    description: 'The path to the package.json'
    default: './package.json'

  changelog-path:
    description: 'The path to the CHANGELOG.md'
    default: './CHANGELOG.md'

  branch:
    description: 'The remote refs for git push'
    default: "main"

  commit-template:
    description: 'Template for commit message using $version$ as var'
    default: 'chore(release): 🔖 _version_ [skip ci]'

  githubToken:
    description: 'GITHUB_TOKEN allowing to push on repo'

outputs:
  new-version:
    description: Nouvelle version selectionnée par semantic
    value: ${{ steps.extract-version.outputs.value }}

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Load Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '19.7.0'
      cache: 'yarn'
      cache-dependency-path: yarn.lock

  - name: Run packaging using npx
    id: packaging
    run: 
      npx @kezios/github-action-packaging@latest node 
      --package-uri=${{ inputs.package-path }} 
      --changelog-uri=${{ inputs.changelog-path }}
      --branch=${{ inputs.branch }}
    shell: bash

  - name: Extract version from package.json
    uses: amochkin/gha-json-value@v1-rc5
    id: extract-version
    with:
      property: version

  - name: Prepare commit message
    id: prepare-commit-message
    run: |
      str="${{ inputs.commit-template }}";
      oldstr="${{ steps.extract-version.outputs.value }}";
      newstr="1.0.1";
      result=$(echo $str | sed "s/$oldstr/$newstr/");
      echo "message=$result" >> $GITHUB_OUTPUT;
    shell: bash

  - name: Add and commit changes
    id: commit
    if: ${{ inputs.enable-commit-and-push == 'true' }}
    uses: EndBug/add-and-commit@v9
    with:
      message: ${{ steps.prepare-commit-message.outputs.message }}  
      add: ${{ inputs.staging-path }}

  - name: Push changes to protected branch
    if: ${{ inputs.enable-commit-and-push == 'true' && steps.commit.outputs.committed == 'true' }}
    uses: CasperWA/push-protected@v2
    with:
      branch: ${{ inputs.branch }}
      token: ${{ inputs.githubToken }}
