name: 'Kezios packaging & commit'

description: |
  This GitHub Action runs a packaging Node script to create new version & update changelog.

inputs:
  enable-commit-and-push: 
    description: 'Will create commit & push change'
    default: "true"
  
  staging-path:
    description: 'Args of "git add"'
    default: "."

  package-path:
    description: 'The path to the package.json'
    default: './package.json'

  changelog-path:
    description: 'The path to the CHANGELOG.md'
    default: './CHANGELOG.md'

  branch:
    description: 'The remote refs for git push'
    default: "main"

  commit-template:
    description: 'Template for commit message using $version$ as var'
    default: 'chore(release): 🔖 _version_ [skip ci]'

  github-token:
    description: 'GITHUB_TOKEN allowing to push on repo & access package'

outputs:
  new-version:
    description: Nouvelle version selectionnée par semantic
    value: ${{ steps.extract-version.outputs.value }}

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Load Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 19
      cache: 'yarn'
      cache-dependency-path: yarn.lock

  - name: Run packaging using npx
    id: packaging
    run: |
      touch .nprmc
      echo "@kezios:registry=https://npm.pkg.github.com/" >> .npmrc
      echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-token }}" >> .npmrc
      npx @kezios/github-action-packaging@latest node --package-uri=${{ inputs.package-path }} --changelog-uri=${{ inputs.changelog-path }} --branch=${{ inputs.branch }}
      rm .npmrc
    shell: bash

  - name: Extract version from package.json
    if: ${{ steps.packaging.outputs.status == "success" }}
    uses: amochkin/gha-json-value@v1-rc5
    id: extract-version
    with:
      property: version

  - name: Prepare commit message
    if: ${{ steps.packaging.outputs.status == "success" }}
    id: prepare-commit-message
    run: |
      str="${{ inputs.commit-template }}";
      oldstr="_version_";
      newstr="${{ steps.extract-version.outputs.value }}";
      result=$(echo $str | sed "s/$oldstr/$newstr/");
      echo "message=$result" >> $GITHUB_OUTPUT;
    shell: bash

  - name: Add and commit changes
    id: commit
    if: ${{ inputs.enable-commit-and-push == 'true' && steps.packaging.outputs.status == "success" }}
    uses: EndBug/add-and-commit@v9
    with:
      message: ${{ steps.prepare-commit-message.outputs.message }}  
      add: ${{ inputs.staging-path }}

  - name: Push changes to protected branch
    if: ${{ inputs.enable-commit-and-push == 'true' && steps.commit.outputs.committed == 'true' && steps.packaging.outputs.status == "success" }}
    uses: CasperWA/push-protected@v2
    with:
      branch: ${{ inputs.branch }}
      token: ${{ inputs.github-token }}
